import type { FamilyProfile, Profile } from '../types';

export const sampleProfile: Profile = {
  userId: 'user-1',
  firstName: 'Asha',
  lastName: 'Verma',
  gender: 'female',
  dateOfBirth: '1997-05-12',
  age: 28,
  religion: 'Hindu',
  motherTongue: 'Hindi',
  height: 165,
  education: 'MBA',
  profession: 'Product Manager',
  company: 'Acme',
  salaryRange: '20-35 LPA',
  location: 'Bengaluru',
  state: 'Karnataka',
  country: 'India',
  bio: 'Curious, thoughtful, and family-oriented.',
  interests: ['Travel', 'Music', 'Coffee', 'Reading'],
  photoUrl: '',
  maritalStatus: 'Never Married',
  familyType: 'Nuclear',
  diet: 'Vegetarian',
  smoking: 'No',
  drinking: 'Socially',
  lookingFor: 'Kindness and compatibility.',
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-02T00:00:00.000Z',
  matchPercentage: 82,
  recommendationScore: 91,
  recommendationReasons: ['Shared values', 'Similar profession'],
  recommendationGeneratedAt: '2026-01-02T00:00:00.000Z',
};

export const sampleFamilyProfile: FamilyProfile = {
  userId: 'user-1',
  fatherName: 'Rajesh Verma',
  fatherOccupation: 'Business Owner',
  motherName: 'Sunita Verma',
  motherOccupation: 'Teacher',
  siblings: '1 younger brother',
  familyIncome: '25-40 LPA',
  familyValues: 'Moderate',
  aboutFamily: 'Close-knit and progressive family.',
  contactPerson: 'Rajesh Verma',
  contactPhone: '9999999999',
  familyLocation: 'Bengaluru',
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-02T00:00:00.000Z',
};
