AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Onboarding Document Tracker (Multi-tenant SaaS) — SES receives employee emails
  with documents, stores in S3, S3 notifies SQS, Lambda processes from SQS to
  resolve the tenant, parse attachments, upload to tenant's OneDrive, and notify
  tenant's HR via SES.  All tenant data is encrypted at rest with a dedicated
  KMS key and Azure credentials are stored in AWS Secrets Manager.

Parameters:
  ApiKey:
    Type: String
    NoEcho: true
    Description: API key for tenant management endpoints
  OnboardingDomain:
    Type: String
    Description: >
      Domain for receiving onboarding emails (e.g. docs.example.com).
      Each tenant gets a unique address on this domain (e.g. acme@docs.example.com).
  MaxRetries:
    Type: Number
    Default: 3
    Description: Number of times SQS retries a failed message before sending to DLQ
  CorsAllowedOrigins:
    Type: String
    Default: '*'
    Description: Comma-separated list of allowed CORS origins (restrict in production)

Globals:
  Function:
    Timeout: 300
    Runtime: nodejs20.x
    MemorySize: 512
    Environment:
      Variables:
        NODE_ENV: production

Resources:

  # ── KMS: customer-managed key for encrypting all tenant data at rest ──
  TenantDataKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Encrypts all tenant data at rest (DynamoDB, S3, SQS, Secrets Manager)
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: RootAccountAccess
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: LambdaKeyUsage
            Effect: Allow
            Principal:
              AWS: !GetAtt ProcessEmailFunctionRole.Arn
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
              - kms:DescribeKey
            Resource: '*'
          - Sid: SESKeyUsage
            Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: '*'
            Condition:
              StringEquals:
                'kms:ViaService': !Sub 's3.${AWS::Region}.amazonaws.com'
          - Sid: SQSKeyUsage
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: '*'

  TenantDataKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/${AWS::StackName}-tenant-data-key'
      TargetKeyId: !Ref TenantDataKey

  # ── S3 Bucket: stores raw emails deposited by SES (encrypted) ──
  EmailBucket:
    Type: AWS::S3::Bucket
    DependsOn: EmailQueuePolicy
    Properties:
      BucketName: !Sub '${AWS::StackName}-emails'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !GetAtt TenantDataKey.Arn
            BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpireProcessedEmails
            Status: Enabled
            ExpirationInDays: 90
          - Id: ExpireOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt EmailProcessingQueue.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: incoming/

  EmailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref EmailBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSESPut
            Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${EmailBucket.Arn}/incoming/*'
            Condition:
              StringEquals:
                'AWS:SourceAccount': !Ref 'AWS::AccountId'
          - Sid: DenyUnencryptedUploads
            Effect: Deny
            Principal: '*'
            Action: s3:PutObject
            Resource: !Sub '${EmailBucket.Arn}/*'
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': 'aws:kms'
          - Sid: EnforceSSLOnly
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${EmailBucket.Arn}'
              - !Sub '${EmailBucket.Arn}/*'
            Condition:
              Bool:
                'aws:SecureTransport': false

  # ── SQS: buffers S3 event notifications with retry + DLQ (encrypted) ──
  EmailProcessingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-email-dlq'
      MessageRetentionPeriod: 1209600  # 14 days
      KmsMasterKeyId: !GetAtt TenantDataKey.Arn

  EmailProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-email-queue'
      VisibilityTimeout: 360  # 6× Lambda timeout for safety margin
      MessageRetentionPeriod: 345600  # 4 days
      KmsMasterKeyId: !GetAtt TenantDataKey.Arn
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt EmailProcessingDLQ.Arn
        maxReceiveCount: !Ref MaxRetries

  EmailQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref EmailProcessingQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowS3SendMessage
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt EmailProcessingQueue.Arn
            Condition:
              ArnLike:
                'aws:SourceArn': !Sub 'arn:aws:s3:::${AWS::StackName}-emails'

  # ── IAM Role for Lambda (defined explicitly for KMS key policy reference) ──
  ProcessEmailFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchGetItem
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${AWS::StackName}-tracking-*'
                  - !GetAtt TenantsTable.Arn
                  - !Sub '${TenantsTable.Arn}/index/*'
              - Effect: Allow
                Action:
                  - dynamodb:CreateTable
                  - dynamodb:DeleteTable
                  - dynamodb:DescribeTable
                  - dynamodb:TagResource
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${AWS::StackName}-tracking-*'
        - PolicyName: S3ReadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub '${EmailBucket.Arn}/incoming/*'
        - PolicyName: SQSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt EmailProcessingQueue.Arn
        - PolicyName: SESAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource:
                  - !Sub 'arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/${OnboardingDomain}'
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:CreateSecret
                  - secretsmanager:UpdateSecret
                  - secretsmanager:DeleteSecret
                  - secretsmanager:TagResource
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${AWS::StackName}/tenants/*'
        - PolicyName: KMSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                  - kms:DescribeKey
                Resource: !GetAtt TenantDataKey.Arn

  # ── Lambda: processes emails from SQS ──
  ProcessEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/process-emails.handler.handler
      Description: Parses onboarding emails from S3 (via SQS), resolves tenant, uploads documents to OneDrive, notifies HR
      Role: !GetAtt ProcessEmailFunctionRole.Arn
      ReservedConcurrentExecutions: 5
      Environment:
        Variables:
          API_KEY: !Ref ApiKey
          DYNAMODB_TABLE_PREFIX: !Sub '${AWS::StackName}-tracking'
          TENANTS_TABLE: !Ref TenantsTable
          EMAIL_BUCKET: !Ref EmailBucket
          KMS_KEY_ARN: !GetAtt TenantDataKey.Arn
          SECRETS_PREFIX: !Sub '${AWS::StackName}/tenants'
          CORS_ALLOWED_ORIGINS: !Ref CorsAllowedOrigins
      Events:
        SQSEmailReceived:
          Type: SQS
          Properties:
            Queue: !GetAtt EmailProcessingQueue.Arn
            BatchSize: 5
            FunctionResponseTypes:
              - ReportBatchItemFailures

  # ── SES Receipt Rule: receives email for all tenants on the domain ──
  SesReceiptRuleSet:
    Type: AWS::SES::ReceiptRuleSet
    Properties:
      RuleSetName: !Sub '${AWS::StackName}-ruleset'

  SesReceiptRule:
    Type: AWS::SES::ReceiptRule
    DependsOn:
      - EmailBucketPolicy
    Properties:
      RuleSetName: !Ref SesReceiptRuleSet
      Rule:
        Name: !Sub '${AWS::StackName}-receive-docs'
        Enabled: true
        ScanEnabled: true
        TlsPolicy: Require
        Recipients:
          - !Ref OnboardingDomain
        Actions:
          - S3Action:
              BucketName: !Ref EmailBucket
              ObjectKeyPrefix: incoming/
              KmsKeyArn: !GetAtt TenantDataKey.Arn

  # ── DynamoDB: per-tenant tracking tables are created dynamically ──
  # Each tenant gets a dedicated table named ${StackName}-tracking-${tenantId}
  # created/deleted via the tenant.service during tenant lifecycle.

  # ── DynamoDB: tenant configurations (encrypted, no secrets in records) ──
  TenantsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-tenants'
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !GetAtt TenantDataKey.Arn
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: receivingEmail
          AttributeType: S
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: receivingEmail-index
          KeySchema:
            - AttributeName: receivingEmail
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Project
          Value: onboarding-doc-tracker

Outputs:
  ProcessEmailFunctionArn:
    Description: ARN of the email processing Lambda function
    Value: !GetAtt ProcessEmailFunction.Arn
  EmailBucketName:
    Description: S3 bucket receiving emails from SES
    Value: !Ref EmailBucket
  EmailProcessingQueueUrl:
    Description: SQS queue URL for email processing
    Value: !Ref EmailProcessingQueue
  EmailProcessingDLQUrl:
    Description: Dead-letter queue URL for failed email processing
    Value: !Ref EmailProcessingDLQ
  TrackingTablePrefix:
    Description: Prefix for per-tenant DynamoDB tracking tables (each tenant gets ${prefix}-${tenantId})
    Value: !Sub '${AWS::StackName}-tracking'
  TenantsTableName:
    Description: DynamoDB table storing tenant configurations
    Value: !Ref TenantsTable
  SesRuleSetName:
    Description: SES receipt rule set (must be activated manually after deploy)
    Value: !Ref SesReceiptRuleSet
  TenantDataKeyArn:
    Description: KMS key ARN used for encrypting all tenant data
    Value: !GetAtt TenantDataKey.Arn
