[default.deploy.parameters]
stack_name = "content-cms-base-dev"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = false
resolve_s3 = true
region = "us-east-1"
parameter_overrides = "Environment=dev"

[staging.deploy.parameters]
stack_name = "content-cms-base-staging"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"
parameter_overrides = "Environment=staging"

[prod.deploy.parameters]
stack_name = "content-cms-base-prod"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"
parameter_overrides = "Environment=prod"
